#!/usr/bin/env python
# encoding:utf8

"""
    DragonPy - Dragon 32 emulator in Python
    =======================================

    :created: 2014 by Jens Diemer - www.jensdiemer.de
    :copyleft: 2014 by the DragonPy team, see AUTHORS for more details.
    :license: GNU GPL v3 or above, see LICENSE for more details.
"""

import Tkinter
import math

from dragonpy.Dragon32.dragon_charmap import NORMAL, get_hex_color, COLORS, INVERTED
from dragonpy.utils.logging_utils import log

BACKGROUND_CHAR = "."
FOREGROUND_CHAR = "X"
CHARS_DICT = {
    u'@': (# COMMERCIAL AT
        "........",
        "........",
        "........",
        "...XXX..",
        "..X...X.",
        "......X.",
        "...XX.X.",
        "..X.X.X.",
        "..X.X.X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'A': (# LATIN CAPITAL LETTER A
        "........",
        "........",
        "........",
        "....X...",
        "...X.X..",
        "..X...X.",
        "..X...X.",
        "..XXXXX.",
        "..X...X.",
        "..X...X.",
        "........",
        "........",
        "........",
    ),
    u'B': (# LATIN CAPITAL LETTER B
        "........",
        "........",
        "........",
        "..XXXX..",
        "...X..X.",
        "...X..X.",
        "...XXX..",
        "...X..X.",
        "...X..X.",
        "..XXXX..",
        "........",
        "........",
        "........",
    ),
    u'C': (# LATIN CAPITAL LETTER C
        "........",
        "........",
        "........",
        "...XXX..",
        "..X...X.",
        "..X.....",
        "..X.....",
        "..X.....",
        "..X...X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'D': (# LATIN CAPITAL LETTER D
        "........",
        "........",
        "........",
        "..XXXX..",
        "...X..X.",
        "...X..X.",
        "...X..X.",
        "...X..X.",
        "...X..X.",
        "..XXXX..",
        "........",
        "........",
        "........",
    ),
    u'E': (# LATIN CAPITAL LETTER E
        "........",
        "........",
        "........",
        "..XXXXX.",
        "..X.....",
        "..X.....",
        "..XXXX..",
        "..X.....",
        "..X.....",
        "..XXXXX.",
        "........",
        "........",
        "........",
    ),
    u'F': (# LATIN CAPITAL LETTER F
        "........",
        "........",
        "........",
        "..XXXXX.",
        "..X.....",
        "..X.....",
        "..XXXX..",
        "..X.....",
        "..X.....",
        "..X.....",
        "........",
        "........",
        "........",
    ),
    u'G': (# LATIN CAPITAL LETTER G
        "........",
        "........",
        "........",
        "...XXXX.",
        "..X.....",
        "..X.....",
        "..X..XX.",
        "..X...X.",
        "..X...X.",
        "...XXXX.",
        "........",
        "........",
        "........",
    ),
    u'H': (# LATIN CAPITAL LETTER H
        "........",
        "........",
        "........",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..XXXXX.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "........",
        "........",
        "........",
    ),
    u'I': (# LATIN CAPITAL LETTER I
        "........",
        "........",
        "........",
        "...XXX..",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'J': (# LATIN CAPITAL LETTER J
        "........",
        "........",
        "........",
        "......X.",
        "......X.",
        "......X.",
        "......X.",
        "..X...X.",
        "..X...X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'K': (# LATIN CAPITAL LETTER K
        "........",
        "........",
        "........",
        "..X...X.",
        "..X..X..",
        "..X.X...",
        "..XX....",
        "..X.X...",
        "..X..X..",
        "..X...X.",
        "........",
        "........",
        "........",
    ),
    u'L': (# LATIN CAPITAL LETTER L
        "........",
        "........",
        "........",
        "..X.....",
        "..X.....",
        "..X.....",
        "..X.....",
        "..X.....",
        "..X.....",
        "..XXXXX.",
        "........",
        "........",
        "........",
    ),
    u'M': (# LATIN CAPITAL LETTER M
        "........",
        "........",
        "........",
        "..X...X.",
        "..XX.XX.",
        "..X.X.X.",
        "..X.X.X.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "........",
        "........",
        "........",
    ),
    u'N': (# LATIN CAPITAL LETTER N
        "........",
        "........",
        "........",
        "..X...X.",
        "..XX..X.",
        "..X.X.X.",
        "..X..XX.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "........",
        "........",
        "........",
    ),
    u'O': (# LATIN CAPITAL LETTER O
        "........",
        "........",
        "........",
        "..XXXXX.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..XXXXX.",
        "........",
        "........",
        "........",
    ),
    u'P': (# LATIN CAPITAL LETTER P
        "........",
        "........",
        "........",
        "..XXXX..",
        "..X...X.",
        "..X...X.",
        "..XXXX..",
        "..X.....",
        "..X.....",
        "..X.....",
        "........",
        "........",
        "........",
    ),
    u'Q': (# LATIN CAPITAL LETTER Q
        "........",
        "........",
        "........",
        "...XXX..",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..X.X.X.",
        "..X..X..",
        "...XX.X.",
        "........",
        "........",
        "........",
    ),
    u'R': (# LATIN CAPITAL LETTER R
        "........",
        "........",
        "........",
        "..XXXX..",
        "..X...X.",
        "..X...X.",
        "..XXXX..",
        "..X.X...",
        "..X..X..",
        "..X...X.",
        "........",
        "........",
        "........",
    ),
    u'S': (# LATIN CAPITAL LETTER S
        "........",
        "........",
        "........",
        "...XXX..",
        "..X...X.",
        "...X....",
        "....X...",
        ".....X..",
        "..X...X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'T': (# LATIN CAPITAL LETTER T
        "........",
        "........",
        "........",
        "..XXXXX.",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u'U': (# LATIN CAPITAL LETTER U
        "........",
        "........",
        "........",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'V': (# LATIN CAPITAL LETTER V
        "........",
        "........",
        "........",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "...X.X..",
        "...X.X..",
        "....X...",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u'W': (# LATIN CAPITAL LETTER W
        "........",
        "........",
        "........",
        "..X...X.",
        "..X...X.",
        "..X...X.",
        "..X.X.X.",
        "..X.X.X.",
        "..XX.XX.",
        "..X...X.",
        "........",
        "........",
        "........",
    ),
    u'X': (# LATIN CAPITAL LETTER X
        "........",
        "........",
        "........",
        "..X...X.",
        "..X...X.",
        "...X.X..",
        "....X...",
        "...X.X..",
        "..X...X.",
        "..X...X.",
        "........",
        "........",
        "........",
    ),
    u'Y': (# LATIN CAPITAL LETTER Y
        "........",
        "........",
        "........",
        "..X...X.",
        "..X...X.",
        "...X.X..",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u'Z': (# LATIN CAPITAL LETTER Z
        "........",
        "........",
        "........",
        "..XXXXX.",
        "......X.",
        ".....X..",
        "....X...",
        "...X....",
        "..X.....",
        "..XXXXX.",
        "........",
        "........",
        "........",
    ),
    u'[': (# LEFT SQUARE BRACKET
        "........",
        "........",
        "........",
        "..XXX...",
        "..X.....",
        "..X.....",
        "..X.....",
        "..X.....",
        "..X.....",
        "..XXX...",
        "........",
        "........",
        "........",
    ),
    u'\\': (# REVERSE SOLIDUS
        "........",
        "........",
        "........",
        "..X.....",
        "..X.....",
        "...X....",
        "....X...",
        ".....X..",
        "......X.",
        "......X.",
        "........",
        "........",
        "........",
    ),
    u']': (# RIGHT SQUARE BRACKET
        "........",
        "........",
        "........",
        "....XXX.",
        "......X.",
        "......X.",
        "......X.",
        "......X.",
        "......X.",
        "....XXX.",
        "........",
        "........",
        "........",
    ),
    u'\u2191': (# UPWARDS ARROW
        "........",
        "........",
        "........",
        "....X...",
        "...XXX..",
        "..X.X.X.",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u'\u2190': (# LEFTWARDS ARROW
        "........",
        "........",
        "........",
        "........",
        "....X...",
        "...X....",
        "..XXXXX.",
        "...X....",
        "....X...",
        "........",
        "........",
        "........",
        "........",
    ),
    u' ': (# SPACE
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
    ),
    u'!': (# EXCLAMATION MARK
        "........",
        "........",
        "........",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "........",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u'"': (# QUOTATION MARK
        "........",
        "........",
        "........",
        "...X.X..",
        "...X.X..",
        "...X.X..",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
    ),
    u'#': (# NUMBER SIGN
        "........",
        "........",
        "........",
        "...X.X..",
        "...X.X..",
        "..XX.XX.",
        "........",
        "..XX.XX.",
        "...X.X..",
        "...X.X..",
        "........",
        "........",
        "........",
    ),
    u'$': (# DOLLAR SIGN
        "........",
        "........",
        "........",
        "....X...",
        "...XXXX.",
        "..X.....",
        "...XXX..",
        "......X.",
        "..XXXX..",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u'%': (# PERCENT SIGN
        "........",
        "........",
        "........",
        "..XX..X.",
        "..XX..X.",
        ".....X..",
        "....X...",
        "...X....",
        "..X..XX.",
        "..X..XX.",
        "........",
        "........",
        "........",
    ),
    u'&': (# AMPERSAND
        "........",
        "........",
        "........",
        "...X....",
        "..X.X...",
        "..X.X...",
        "...X....",
        "..X.X.X.",
        "..X..X..",
        "...XX.X.",
        "........",
        "........",
        "........",
    ),
    u"'": (# APOSTROPHE
        "........",
        "........",
        "........",
        "...XX...",
        "...XX...",
        "...XX...",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
    ),
    u'(': (# LEFT PARENTHESIS
        "........",
        "........",
        "........",
        "....X...",
        "...X....",
        "..X.....",
        "..X.....",
        "..X.....",
        "...X....",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u')': (# RIGHT PARENTHESIS
        "........",
        "........",
        "........",
        "....X...",
        ".....X..",
        "......X.",
        "......X.",
        "......X.",
        ".....X..",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u'*': (# ASTERISK
        "........",
        "........",
        "........",
        "........",
        "....X...",
        "...XXX..",
        "..XXXXX.",
        "...XXX..",
        "....X...",
        "........",
        "........",
        "........",
        "........",
    ),
    u'+': (# PLUS SIGN
        "........",
        "........",
        "........",
        "........",
        "....X...",
        "....X...",
        "..XXXXX.",
        "....X...",
        "....X...",
        "........",
        "........",
        "........",
        "........",
    ),
    u',': (# COMMA
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "..XX....",
        "..XX....",
        "...X....",
        "..X.....",
        "........",
        "........",
        "........",
    ),
    u'-': (# HYPHEN-MINUS
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "..XXXXX.",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
    ),
    u'.': (# FULL STOP
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "..XX....",
        "..XX....",
        "........",
        "........",
        "........",
    ),
    u'/': (# SOLIDUS
        "........",
        "........",
        "........",
        "......X.",
        "......X.",
        ".....X..",
        "....X...",
        "...X....",
        "..X.....",
        "..X.....",
        "........",
        "........",
        "........",
    ),
    u'0': (# DIGIT ZERO
        "........",
        "........",
        "........",
        "...XX...",
        "..X..X..",
        "..X..X..",
        "..X..X..",
        "..X..X..",
        "..X..X..",
        "...XX...",
        "........",
        "........",
        "........",
    ),
    u'1': (# DIGIT ONE
        "........",
        "........",
        "........",
        "....X...",
        "...XX...",
        "....X...",
        "....X...",
        "....X...",
        "....X...",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'2': (# DIGIT TWO
        "........",
        "........",
        "........",
        "...XXX..",
        "..X...X.",
        "......X.",
        "...XXX..",
        "..X.....",
        "..X.....",
        "..XXXXX.",
        "........",
        "........",
        "........",
    ),
    u'3': (# DIGIT THREE
        "........",
        "........",
        "........",
        "...XXX..",
        "..X...X.",
        "......X.",
        "....XX..",
        "......X.",
        "..X...X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'4': (# DIGIT FOUR
        "........",
        "........",
        "........",
        ".....X..",
        "....XX..",
        "...X.X..",
        "..XXXXX.",
        ".....X..",
        ".....X..",
        ".....X..",
        "........",
        "........",
        "........",
    ),
    u'5': (# DIGIT FIVE
        "........",
        "........",
        "........",
        "..XXXXX.",
        "..X.....",
        "..XXXX..",
        "......X.",
        "......X.",
        "..X...X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'6': (# DIGIT SIX
        "........",
        "........",
        "........",
        "...XXX..",
        "..X.....",
        "..X.....",
        "..XXXX..",
        "..X...X.",
        "..X...X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'7': (# DIGIT SEVEN
        "........",
        "........",
        "........",
        "..XXXXX.",
        "......X.",
        ".....X..",
        "....X...",
        "...X....",
        "..X.....",
        "..X.....",
        "........",
        "........",
        "........",
    ),
    u'8': (# DIGIT EIGHT
        "........",
        "........",
        "........",
        "...XXX..",
        "..X...X.",
        "..X...X.",
        "...XXX..",
        "..X...X.",
        "..X...X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u'9': (# DIGIT NINE
        "........",
        "........",
        "........",
        "...XXX..",
        "..X...X.",
        "..X...X.",
        "...XXXX.",
        "......X.",
        "......X.",
        "...XXX..",
        "........",
        "........",
        "........",
    ),
    u':': (# COLON
        "........",
        "........",
        "........",
        "........",
        "...XX...",
        "...XX...",
        "........",
        "...XX...",
        "...XX...",
        "........",
        "........",
        "........",
        "........",
    ),
    u';': (# SEMICOLON
        "........",
        "........",
        "........",
        "...XX...",
        "...XX...",
        "........",
        "...XX...",
        "...XX...",
        "....X...",
        "...X....",
        "........",
        "........",
        "........",
    ),
    u'<': (# LESS-THAN SIGN
        "........",
        "........",
        "........",
        ".....X..",
        "....X...",
        "...X....",
        "..X.....",
        "...X....",
        "....X...",
        ".....X..",
        "........",
        "........",
        "........",
    ),
    u'=': (# EQUALS SIGN
        "........",
        "........",
        "........",
        "........",
        "........",
        "..XXXXX.",
        "........",
        "..XXXXX.",
        "........",
        "........",
        "........",
        "........",
        "........",
    ),
    u'>': (# GREATER-THAN SIGN
        "........",
        "........",
        "........",
        "...X....",
        "....X...",
        ".....X..",
        "......X.",
        ".....X..",
        "....X...",
        "...X....",
        "........",
        "........",
        "........",
    ),
    u'?': (# QUESTION MARK
        "........",
        "........",
        "........",
        "...XX...",
        "..X..X..",
        ".....X..",
        "....X...",
        "....X...",
        "........",
        "....X...",
        "........",
        "........",
        "........",
    ),
    u'\u2588':(#   FULL BLOCK
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
    ),
    u'\u259b':(#   QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
    ),
    u'\u259c':(#   QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
    ),
    u'\u2580':(#   UPPER HALF BLOCK
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
    ),
    u'\u2599':(#   QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
    ),
    u'\u258c':(#   LEFT HALF BLOCK
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
    ),
    u'\u259a':(#   QUADRANT UPPER LEFT AND LOWER RIGHT
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
    ),
    u'\u2598':(#   QUADRANT UPPER LEFT
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
    ),
    u'\u259f':(#   QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
    ),
    u'\u259e':(#   QUADRANT UPPER RIGHT AND LOWER LEFT
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
    ),
    u'\u2590':(#   RIGHT HALF BLOCK
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
    ),
    u'\u259d':(#   QUADRANT UPPER RIGHT
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
    ),
    u'\u2584':(#   LOWER HALF BLOCK
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
        "XXXXXXXX",
    ),
    u'\u2596':(#   QUADRANT LOWER LEFT
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
        "XXXX....",
    ),
    u'\u2597':(#   QUADRANT LOWER RIGHT
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
        "....XXXX",
    ),
}




class TkFont(object):
    """
    Important is that image must be bind to a object, without:
    the garbage-collection by Python will "remove" the created images in Tkinter.Canvas!
    """
    def __init__(self, chars_dict, scale_factor):
        assert isinstance(scale_factor, int)
        assert scale_factor > 0

        self.chars_dict = chars_dict
        self.scale_factor = scale_factor

        temp = chars_dict["X"]
        self.width_real = len(temp[0])
        self.height_real = len(temp)

        self.width_scaled = self.width_real * self.scale_factor
        self.height_scaled = self.height_real * self.scale_factor

        log.critical("Every character is %ipx x %ipx (incl. scale factor: %i)",
            self.width_scaled, self.height_scaled,
            self.scale_factor
        )

    def get_char(self, char, color):
        log.critical("Generate char %s %s", repr(char), color)
        try:
            char_data = self.chars_dict[char]
        except KeyError:
            log.log(99, "Error: character %s is not in CHARS_DICT !", repr(char))
#             return self._generate_char(char="?", color=color)
            return self.get_char(char="?", color=color)

        foreground, background = get_hex_color(color)
        foreground = "#%s" % foreground
        background = "#%s" % background

        img = Tkinter.PhotoImage(
            width=self.width_scaled,
            height=self.height_scaled
        )

        # Fill the character pixels without padding
        for y, line in enumerate(char_data):
            for x, bit in enumerate(line):
                if bit == BACKGROUND_CHAR:
                    color = background
                else:
                    assert bit == FOREGROUND_CHAR
                    color = foreground

                img.put(color, (x, y))

        # resize the character
        if self.scale_factor > 1:
            img = img.zoom(self.scale_factor, self.scale_factor)

        return img


class TestTkFont(object):
    def __init__(self, row_count, tk_font, colors):
        self.row_count = row_count
        self.tk_font = tk_font
        self.colors = colors
        self.color_index = 0
        self.current_color = self.colors[self.color_index]

        self.root = Tkinter.Tk()
        self.root.title("TkFont Test")

        self.root.bind('<Down>', self.event_arrow_down)
        self.root.bind('<Up>', self.event_arrow_up)

        self.total_width = self.tk_font.width_scaled * self.row_count
        self.total_height = int(
            self.tk_font.height_scaled * math.ceil(
                len(self.tk_font.chars_dict) / self.row_count + 1
            )
        )

        print "Window/Canvas geometry: %spx x %spx" % (self.total_width, self.total_height)
        self.root.geometry("+%i+%i" % (self.total_width, self.total_height))

        self.canvas = Tkinter.Canvas(self.root,
            width=self.total_width,
            height=self.total_height,
            bd=0,  # Border
            bg="#000000",
        )
        self.canvas.pack()
        self.add_chars()

    def add_chars(self):
        print "Fill with", self.current_color
        chars_dict = self.tk_font.chars_dict
        for no, char in enumerate(sorted(chars_dict.keys())):
            y, x = divmod(no * self.tk_font.width_scaled, self.total_width)
            y *= self.tk_font.height_scaled
#             print "add %s color: %s to %i x %i" % (
#                 repr(char), self.current_color, x, y
#             )
            img = self.tk_font.get_char(char, self.current_color)

            self.canvas.create_image(x, y,
                image=img,
                state="normal",
                anchor=Tkinter.NW  # NW == NorthWest
            )
            # self.root.update() # Not needed here!

    def event_arrow_up(self, event):
        self.color_index += 1
        if self.color_index >= len(self.colors):
            self.color_index = 0
        self.current_color = self.colors[self.color_index]
        self.add_chars()

    def event_arrow_down(self, event):
        self.color_index -= 1
        if self.color_index < 0:
            self.color_index = len(self.colors) - 1
        self.current_color = self.colors[self.color_index]
        self.add_chars()

    def mainloop(self):
        self.root.mainloop()


def test_dict(chars_dict, width, height):
    for char, data in sorted(chars_dict.items()):
        if len(data) != height:
            print "Char %s has wrong height / row count !" % repr(char)
            print "Should have %i rows, but has: %i rows" % (height, len(data))
        for line in data:
            if len(line) != width:
                print "Char %s has wrong width / column count !" % repr(char)
                print "Should have %i columns, but has: %i columns" % (width, len(line))


if __name__ == "__main__":
    test_dict(CHARS_DICT, width=8, height=13)

#     scale_factor = 1
#     scale_factor = 2
#     scale_factor = 3
    scale_factor = 4
#     scale_factor = 8
    tk_font = TkFont(
        CHARS_DICT, scale_factor,
    )

    colors = (NORMAL, INVERTED) + COLORS

    t = TestTkFont(
        row_count=10,
        tk_font=tk_font,
        colors=colors,
    )
    t.mainloop()
    print " --- END --- "
