#!/usr/bin/env python
# coding: utf-8

"""
    DragonPy - Dragon 32 emulator in Python
    =======================================

    :copyleft: 2014 by the DragonPy team, see AUTHORS for more details.
    :license: GNU GPL v3 or above, see LICENSE for more details.
"""


from dragonpy.cpu6809 import Instruction, hex_repr
import atexit
import os


DEBUG_FILENAME = "../../dragonpy_debug.html"


HTML_OUT = file(DEBUG_FILENAME, "w")
HTML_OUT.write("""<!DOCTYPE html>
<html><head>
<style>
body {
    font-family:"Lucida Console", Monaco, monospace;
    white-space:nowrap;
}
table, th, td{border-collapse:collapse;border:1px solid black;}
th, td {padding:5px;}
</style>
</head><body><h1>DragonPy Debug:</h1>
<table>""")


@atexit.register
def close_html_debug():
    HTML_OUT.write("\n</table>\n")
    HTML_OUT.write(
        "<addr>This file was generated by %s</addr>\n" % os.path.split(__file__)[1]
    )
    HTML_OUT.write("</body></html>")


class InstructionHTMLdebug(Instruction):
    def __init__(self, *args, **kwargs):
        super(InstructionHTMLdebug, self).__init__(*args, **kwargs)

    def call_instr_func(self, *args, **kwargs):
        super(InstructionHTMLdebug, self).call_instr_func(*args, **kwargs)

        HTML_OUT.write("<tr>\n")
        HTML_OUT.write("<td>%x</td>" % self.cpu.last_op_address)
        HTML_OUT.write("<td>%x</td>" % self.opcode)
        HTML_OUT.write("<td>%s</td>" % self.data["mnemonic"])
        HTML_OUT.write("<td>%s</td>" % hex_repr(self.op_kwargs))
        HTML_OUT.write("<td>%s</td>" % self.cpu.get_info)
        HTML_OUT.write("<td>%s</td>" % self.cpu.cc.get_info)
        HTML_OUT.write("<td>%s</td>" % self.cpu.cfg.mem_info.get_shortest(self.cpu.last_op_address))
        HTML_OUT.write("</tr>")
